# Generated by Django 5.0 on 2025-04-25 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photos', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('electricien', 'Électricien'), ('plombier', 'Plombier'), ('macon', 'Maçon'), ('carreleur', 'Carreleur'), ('peintre', 'Peintre'), ('chef_chantier', 'Chef de chantier'), ('etancheur', 'Étancheur'), ('facadier', 'Façadier'), ('plafond_faux', 'Poseur de faux plafonds'), ('menuisier', 'Menuisier'), ('serrurier', 'Serrurier'), ('soudeur', 'Soudeur / Ferronnier'), ('vitrier', 'Vitrier'), ('technicien_aluminium', 'Technicien aluminium'), ('installateur_cuisine', 'Installateur de cuisines'), ('installateur_placard', 'Installateur de placards / dressing'), ('installateur_gaz', 'Installateur de gaz / chauffe-eau'), ('installateur_tv', 'Installateur TV / satellite'), ('staffeur', 'Staffeur / Décorateur en plâtre'), ('technicien_clim', 'Technicien climatisation / frigo'), ('technicien_electromenager', 'Technicien électroménager'), ('technicien_info', 'Technicien informatique'), ('domoticien', 'Spécialiste domotique / maison intelligente'), ('jardinier', 'Jardinier / Paysagiste'), ('bricoleur', 'Bricoleur / Multi-travaux'), ('nettoyeur', 'Nettoyeur'), ('electricien_auto', 'Électricien auto')], max_length=30)),
                ('Note', models.FloatField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
