# Generated by Django 5.0 on 2025-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
