# Generated by Django 5.0 on 2025-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photos',
            field=models.CharField(max_length=200),
        ),
    ]
