# Generated by Django 5.0 on 2025-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_service_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Note',
            field=models.FloatField(null=True),
        ),
    ]
