# Generated by Django 5.0 on 2025-04-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_service_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photos',
            field=models.TextField(),
        ),
    ]
