# Generated by Django 5.0 on 2025-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Note',
            field=models.FloatField(default=0),
        ),
    ]
