# Generated by Django 5.0 on 2025-05-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_service_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
