# Generated by Django 5.0 on 2025-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
