# Generated by Django 5.0 on 2025-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='first',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
