# Generated by Django 5.0 on 2025-06-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
