# Generated by Django 5.1.5 on 2026-01-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='photos',
        ),
        migrations.AlterField(
            model_name='service',
            name='first',
            field=models.ImageField(default='defaults/service.png', upload_to='HeroImage/'),
        ),
        migrations.CreateModel(
            name='Service_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Service/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
