# Generated by Django 5.0 on 2025-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_users_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
