# Generated by Django 5.0 on 2025-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_users_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='profile/default.png', upload_to='profile'),
        ),
    ]
