# Generated by Django 5.0 on 2025-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_users_adresse_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('artisan', 'ARTISAN'), ('client', 'CLIENT'), ('admin', 'admin')], default='client', max_length=30),
        ),
    ]
