# Generated by Django 5.0 on 2025-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adresse',
            field=models.CharField(default='profile/default.png', max_length=30),
        ),
    ]
