# Generated by Django 5.0 on 2025-06-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lat',
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
