# Generated by Django 5.0 on 2025-05-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_alter_demande_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='decription',
            new_name='description',
        ),
    ]
