# Generated by Django 5.0 on 2025-05-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_demande_service_alter_demande_artisan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.demande')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
