# Generated by Django 5.0 on 2025-05-12 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0009_alter_notification_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_artisan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_client_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
