# Generated by Django 5.0 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_alter_demande_artisan_alter_demande_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Fès', 'Fès'), ('Marrakech', 'Marrakech'), ('Tangier', 'Tangier'), ('Sale', 'Sale'), ('Rabat', 'Rabat'), ('Meknès', 'Meknès'), ('Oujda-Angad', 'Oujda-Angad'), ('Kenitra', 'Kenitra'), ('Agadir', 'Agadir'), ('Tétouan', 'Tétouan'), ('Taourirt', 'Taourirt'), ('Temara', 'Temara'), ('Safi', 'Safi'), ('Khénifra', 'Khénifra'), ('El Jadid', 'El Jadid'), ('Laâyoune', 'Laâyoune'), ('Mohammedia', 'Mohammedia'), ('Kouribga', 'Kouribga'), ('Béni Mellal', 'Béni Mellal'), ('Ait Melloul', 'Ait Melloul'), ('Nador', 'Nador'), ('Taza', 'Taza'), ('Settat', 'Settat'), ('Barrechid', 'Barrechid'), ('Al Khmissat', 'Al Khmissat'), ('Inezgane', 'Inezgane'), ('Ksar El Kebir', 'Ksar El Kebir'), ('My Drarga', 'My Drarga'), ('Larache', 'Larache'), ('Guelmim', 'Guelmim'), ('Berkane', 'Berkane'), ('Ad Dakhla', 'Ad Dakhla'), ('Bouskoura', 'Bouskoura'), ('Al Fqih Ben Çalah', 'Al Fqih Ben Çalah'), ('Oued Zem', 'Oued Zem'), ('Sidi Slimane', 'Sidi Slimane'), ('Errachidia', 'Errachidia'), ('Guercif', 'Guercif'), ('Oulad Teïma', 'Oulad Teïma'), ('Ben Guerir', 'Ben Guerir'), ('Sefrou', 'Sefrou'), ('Fnidq', 'Fnidq'), ('Sidi Qacem', 'Sidi Qacem'), ('Tiznit', 'Tiznit'), ('Moulay Abdallah', 'Moulay Abdallah'), ('Youssoufia', 'Youssoufia'), ('Martil', 'Martil'), ('Aïn Harrouda', 'Aïn Harrouda'), ('Souq Sebt Oulad Nemma', 'Souq Sebt Oulad Nemma'), ('Skhirate', 'Skhirate'), ('Ouezzane', 'Ouezzane'), ('Sidi Yahya Zaer', 'Sidi Yahya Zaer'), ('Al Hoceïma', 'Al Hoceïma'), ('M’diq', 'M’diq'), ('Midalt', 'Midalt'), ('Azrou', 'Azrou'), ('El Kelaa des Srarhna', 'El Kelaa des Srarhna'), ('Ain El Aouda', 'Ain El Aouda'), ('Beni Yakhlef', 'Beni Yakhlef'), ('Ad Darwa', 'Ad Darwa'), ('Al Aaroui', 'Al Aaroui'), ('Qasbat Tadla', 'Qasbat Tadla'), ('Boujad', 'Boujad'), ('Jerada', 'Jerada'), ('Mrirt', 'Mrirt'), ('El Aïoun', 'El Aïoun'), ('Azemmour', 'Azemmour'), ('Temsia', 'Temsia'), ('Zagora', 'Zagora'), ('Ait Ourir', 'Ait Ourir'), ('Aziylal', 'Aziylal'), ('Sidi Yahia El Gharb', 'Sidi Yahia El Gharb'), ('Biougra', 'Biougra'), ('Zaïo', 'Zaïo'), ('Aguelmous', 'Aguelmous'), ('El Hajeb', 'El Hajeb'), ('Zeghanghane', 'Zeghanghane'), ('Imzouren', 'Imzouren'), ('Tit Mellil', 'Tit Mellil'), ('Mechraa Bel Ksiri', 'Mechraa Bel Ksiri'), ('Al ’Attawia', 'Al ’Attawia'), ('Demnat', 'Demnat'), ('Arfoud', 'Arfoud'), ('Tameslouht', 'Tameslouht'), ('Bou Arfa', 'Bou Arfa'), ('Sidi Smai’il', 'Sidi Smai’il'), ('Souk et Tnine Jorf el Mellah', 'Souk et Tnine Jorf el Mellah'), ('Mehdya', 'Mehdya'), ('Aïn Taoujdat', 'Aïn Taoujdat'), ('Chichaoua', 'Chichaoua'), ('Tahla', 'Tahla'), ('Oulad Yaïch', 'Oulad Yaïch'), ('Moulay Bousselham', 'Moulay Bousselham'), ('Iheddadene', 'Iheddadene'), ('Missour', 'Missour'), ('Zawyat ech Cheïkh', 'Zawyat ech Cheïkh'), ('Bouknadel', 'Bouknadel'), ('Oulad Tayeb', 'Oulad Tayeb'), ('Oulad Barhil', 'Oulad Barhil'), ('Bir Jdid', 'Bir Jdid'), ('Tifariti', 'Tifariti')], default='none', max_length=30),
        ),
    ]
