# Generated by Django 5.0 on 2025-06-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0011_demande_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
