# Generated by Django 5.0 on 2025-06-03 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_first'),
        ('reviews', '0002_comments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
