# Generated by Django 5.0 on 2025-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_demande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('refused', 'REFUSED'), ('finished', 'FINISHED')], default='pending', max_length=30),
        ),
    ]
